service: notes-app-ext-notify-job
frameworkVersion: ">=2.3.0"

plugins:
  - serverless-bundle

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment:
    stage: ${self:custom.stage}
  tracing:
    lambda: true

  iamRoleStatements:
    - ${file(../../serverless.common.yml):lambdaPolicyXRay}
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: '*'

functions:
  notify:
    handler: notify.main
    events:
      - sns:
        arn: !ImportValue ${self:custom.stage}-ExtNotePurchasedTopicArn

